const world = {
    width: 3000,
    height: 2000,
};

const TILE_SIZE = 64;

const terrainMap = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWSSSSSSWWWWWWWWWW",
    "WWWWWWWWWWWWWSSSSSSSSSSSSWWWWWWW",
    "WWWWWWWWWWWSSSSSSSSSSSSSSSSWWWW",
    "WWWWWWWWWSSSSSSGGGGSSSSSSSSSWWW",
    "WWWWWWSSSSSSGGGGGGGGGGSSSSSSSWW",
    "WWWWWSSSSGGGGGGGGGGGGGGSSSSSSWW",
    "WWWWSSSSGGGGGGGGGGGGGGGGSSSSSWW",
    "WWWSSSSGGGGGGGGGGGGGGGGGGSSSSWW",
    "WWSSSSGGGGGGGGGGGGGGGGGGGGSSSSW",
    "WWSSSGGGGGGGGGGGGGGGGGGGGGSSSSW",
    "WSSSSGGGGGGGGGGGGGGGGGGGGGGSSSW",
    "WSSSGGGGGGGGGGGGGGGGGGGGGGGSSSW",
    "WSSSGGGGGGGGGGGGGGGGGGGGGGSSSSW",
    "WSSSSGGGGGGGGGGGGGGGGGGGGGGSSSW",
    "WWSSSGGGGGGGGGGGGGGGGGGGGGSSSSW",
    "WWSSSSGGGGGGGGGGGGGGGGGGGGSSSSW",
    "WWWSSSSGGGGGGGGGGGGGGGGGGSSSSWW",
    "WWWWSSSSGGGGGGGGGGGGGGGGSSSSWWW",
    "WWWWSSSSSSGGGGGGGGGGGGGGSSSSWWW",
    "WWWWWSSSSSSGGGGGGGGGGGGSSSSWWWW",
    "WWWWWWSSSSSSGGGGGGGGGGSSSSWWWWW",
    "WWWWWWWSSSSSSSSGGGGSSSSSSSWWWWW",
    "WWWWWWWWSSSSSSSSSSSSSSSSSWWWWWW",
    "WWWWWWWWWWSSSSSSSSSSSSSSWWWWWW",
    "WWWWWWWWWWWWSSSSSSSSSSWWWWWWWW",
    "WWWWWWWWWWWWWWSSSSSSWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
];

export { world, TILE_SIZE, terrainMap };